name: 'Update Nix Flake'
description: 'Create a pull-request to update the nix flake'
inputs:
  branch:
    description: 'Name of the branch to create for the pull-request'
    required: false
    default: 'update-nix-flake'
  dir:
    description: 'Directory path to the flake, relative to the directory root'
    required: false
    default: ""
  nix_config:
    description: 'Configuration options to pass to Nix env.'
    required: false
    default: 'extra-experimental-features = nix-command flakes'
  nix_path:
    description:
    required: false
    default: 'nixpkgs=flake:nixpkgs'
  token:
    description: 'Personal Access Token with write permissions on content of the repository'
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare
      id: prepare
      working-directory: "${{ inputs.dir }}"
      run: |
        echo NIX_CONFIG="${{ inputs.nix_config }}" >> $GITHUB_ENV
        echo NIX_PATH="${{ inputs.nix_path }}" >> $GITHUB_ENV
        nix build ".#devShells.x86_64-linux.default" -o "${{ runner.temp }}/flake_original"
      shell: bash

    - name: Update
      id: update
      working-directory: "${{ inputs.dir }}"
      run: |
        nix flake update 2>&1 \
        | tee /dev/stderr \
        | grep -A 2 "Updated input" \
        > ${{ runner.temp }}/nix-flake-update.stdout
        nix build ".#devShells.x86_64-linux.default" -o "${{ runner.temp }}/flake_updated"
      shell: bash

    - name: Check
      id: check
      working-directory: "${{ inputs.dir }}"
      run: |
        nix flake show
        nix flake check
      shell: bash

    - name: Diff
      id: diff
      run: |
        nix store diff-closures "${{ runner.temp }}/flake_original" "${{ runner.temp }}/flake_updated" \
        | tee /dev/stderr \
        > ${{ runner.temp }}/nix-shell-diff.stdout
      shell: bash

    - name: Prepare pull-request
      id: prepare-pr
      run: |
        cat <<EOT | tee ${{ runner.temp }}/pull-request-body.md >> $GITHUB_STEP_SUMMARY
        ### Nix Flake Update
        \`\`\`
        `cat ${{ runner.temp }}/nix-flake-update.stdout`
        \`\`\`
        ### Nix Shell Diff
        \`\`\`
        `cat ${{ runner.temp }}/nix-shell-diff.stdout`
        \`\`\`
        EOT
      shell: bash

    - name: Create pull-request
      id: create-pr
      # The pull-request should only be created on scheduled or dispatched workflows
      if: ${{ contains(fromJSON('["workflow_dispatch", "schedule"]'), github.event_name) }}
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        add-paths: |
          ${{ inputs.dir }}/flake.lock
        base: "main"
        branch: "${{ inputs.branch }}"
        commit-message: "Update Nix Flake"
        delete-branch: true
        title: "Update Nix Flake"
        token: ${{ inputs.token }}
        body-path: "${{ runner.temp }}/pull-request-body.md"
